### ISSUE TITLE
API returns an invalid GeoJson object

### ISSUE THREAD

**Issue by Mloweedgar** [CodeTanzania/emis-alert#6]
The returned Geojson does not follow specifications mentioned here https://tools.ietf.org/html/rfc7946 , therefore the returned GeoJson cannot be displayed on Map

**Comment by lykmapipo** [comment]
@Mloweedgar Please share error trace for the bug...

**Comment by lykmapipo** [comment]
@Mloweedgar You are supposed to use `alert.area.geometry` and not `alert.area` to have a geojson to display on the map using leaflet

**Comment by Mloweedgar** [comment]
@lykmapipo I can display the GeoJson with some work arounds, however I would prefer to receive a valid GeoJson from backend API. I have been looking at official examples here https://leafletjs.com/examples/geojson/,  I have also learnt that createdAt and updatedAt fields are not suppossed to be part of the GeoJSON geometry according this specification https://tools.ietf.org/html/rfc7946. I have displayed the Alerts here https://emis-web-alerts.herokuapp.com/

**Comment by Mloweedgar** [comment]
@lykmapipo I like that the fake alerts can be displayed with Tanzania boundary, can you make them cover small areas so that they may look more realistic( the current ones are too big)

**Comment by lykmapipo** [comment]
@Mloweedgar Sure...`createAt` and `updatedAt` are [foreign members](https://tools.ietf.org/html/rfc7946#page-15) and will be subjected to removal...
